env = Environment()
env.Append(CPPPATH = [ '../' ])

flags = [
	'-g', '-Wall', '-Wextra',

	'-Wno-unused-function',
	'-Wno-implicit-function-declaration',
	'-Wno-int-to-pointer-cast'
]

libs = [
	'zmq'
]

env.Program("lpclient", "lpclient.c", CFLAGS = flags, LIBS = libs + [ 'czmq' ])
env.Program("lpserver", "lpserver.c", CFLAGS = flags, LIBS = libs)